// import 'package:nanohospic/database/entity/sales/test_booking_entity.dart';

// extension TestBookingCopyExtension on TestBooking {
//   TestBooking copyWith({
//     int? id,
//     int? serverId,
//     String? registrationNo,
//     String? mrdNo,
//     DateTime? date,
//     String? phoneNo,
//     String? patientName,
//     String? gender,
//     int? age,
//     String? email,
//     String? address,
//     String? doctorReferrer,
//     String? barcode,
//     String? tokenNo,
//     String? assignTo,
//     String? client,
//     double? total,
//     double? billDiscount,
//     double? totalDiscount,
//     double? gst,
//     double? totalAmount,
//     double? paidAmount,
//     double? balance,
//     double? returnAmount,
//     String? createdAt,
//     String? createdBy,
//     String? lastModified,
//     String? lastModifiedBy,
//     int? isDeleted,
//     String? deletedBy,
//     int? isSynced,
//     String? syncStatus,
//     int? syncAttempts,
//     String? lastSyncError,
//     String? bookingStatus,
//     String? paymentStatus,
//   }) {
//     return TestBooking(
//       id: id ?? this.id,
//       serverId: serverId ?? this.serverId,
//       registrationNo: registrationNo ?? this.registrationNo,
//       mrdNo: mrdNo ?? this.mrdNo,
//       date: date ?? this.date,
//       phoneNo: phoneNo ?? this.phoneNo,
//       patientName: patientName ?? this.patientName,
//       gender: gender ?? this.gender,
//       age: age ?? this.age,
//       email: email ?? this.email,
//       address: address ?? this.address,
//       doctorReferrer: doctorReferrer ?? this.doctorReferrer,
//       barcode: barcode ?? this.barcode,
//       tokenNo: tokenNo ?? this.tokenNo,
//       assignTo: assignTo ?? this.assignTo,
//       client: client ?? this.client,
//       total: total ?? this.total,
//       billDiscount: billDiscount ?? this.billDiscount,
//       totalDiscount: totalDiscount ?? this.totalDiscount,
//       gst: gst ?? this.gst,
//       totalAmount: totalAmount ?? this.totalAmount,
//       paidAmount: paidAmount ?? this.paidAmount,
//       balance: balance ?? this.balance,
//       returnAmount: returnAmount ?? this.returnAmount,
//       createdAt: createdAt ?? this.createdAt,
//       createdBy: createdBy ?? this.createdBy,
//       lastModified: lastModified ?? this.lastModified,
//       lastModifiedBy: lastModifiedBy ?? this.lastModifiedBy,
//       isDeleted: isDeleted ?? this.isDeleted,
//       deletedBy: deletedBy ?? this.deletedBy,
//       isSynced: isSynced ?? this.isSynced,
//       syncStatus: syncStatus ?? this.syncStatus,
//       syncAttempts: syncAttempts ?? this.syncAttempts,
//       lastSyncError: lastSyncError ?? this.lastSyncError,
//       bookingStatus: bookingStatus ?? this.bookingStatus,
//       paymentStatus: paymentStatus ?? this.paymentStatus,
//     );
//   }
// }

// extension BookingItemCopyExtension on BookingItem {
//   BookingItem copyWith({
//     int? id,
//     int? serverId,
//     int? bookingId,
//     String? type,
//     String? name,
//     double? mrp,
//     double? rate,
//     int? quantity,
//     double? gstPercent,
//     double? discountPercent,
//     double? amount,
//     int? testId,
//     int? packageId,
//     String? createdAt,
//     int? isDeleted,
//     int? isSynced,
//   }) {
//     return BookingItem(
//       id: id ?? this.id,
//       serverId: serverId ?? this.serverId,
//       bookingId: bookingId ?? this.bookingId,
//       type: type ?? this.type,
//       name: name ?? this.name,
//       mrp: mrp ?? this.mrp,
//       rate: rate ?? this.rate,
//       quantity: quantity ?? this.quantity,
//       gstPercent: gstPercent ?? this.gstPercent,
//       discountPercent: discountPercent ?? this.discountPercent,
//       amount: amount ?? this.amount,
//       testId: testId ?? this.testId,
//       packageId: packageId ?? this.packageId,
//       createdAt: createdAt ?? this.createdAt,
//       isDeleted: isDeleted ?? this.isDeleted,
//       isSynced: isSynced ?? this.isSynced,
//     );
//   }
// }

// extension PaymentDetailCopyExtension on PaymentDetail {
//   PaymentDetail copyWith({
//     int? id,
//     int? serverId,
//     int? bookingId,
//     String? paymentMode,
//     double? amount,
//     String? referenceNo,
//     String? description,
//     DateTime? paymentDate,
//     String? createdAt,
//     String? createdBy,
//     int? isDeleted,
//     int? isSynced,
//   }) {
//     return PaymentDetail(
//       id: id ?? this.id,
//       serverId: serverId ?? this.serverId,
//       bookingId: bookingId ?? this.bookingId,
//       paymentMode: paymentMode ?? this.paymentMode,
//       amount: amount ?? this.amount,
//       referenceNo: referenceNo ?? this.referenceNo,
//       description: description ?? this.description,
//       paymentDate: paymentDate ?? this.paymentDate,
//       createdAt: createdAt ?? this.createdAt,
//       createdBy: createdBy ?? this.createdBy,
//       isDeleted: isDeleted ?? this.isDeleted,
//       isSynced: isSynced ?? this.isSynced,
//     );
//   }
// }