// // Add this at the end of your test_booking_repo.dart file (BEFORE the class TestBookingRepository)

// import 'package:nanohospic/database/entity/sales/test_booking_entity.dart';

// class TestBookingHelper {
//   static TestBooking copyTestBooking(TestBooking original, {
//     int? id,
//     int? serverId,
//     String? registrationNo,
//     String? mrdNo,
//     DateTime? date,
//     String? phoneNo,
//     String? patientName,
//     String? gender,
//     int? age,
//     String? email,
//     String? address,
//     String? doctorReferrer,
//     String? barcode,
//     String? tokenNo,
//     String? assignTo,
//     String? client,
//     double? total,
//     double? billDiscount,
//     double? totalDiscount,
//     double? gst,
//     double? totalAmount,
//     double? paidAmount,
//     double? balance,
//     double? returnAmount,
//     String? createdAt,
//     String? createdBy,
//     String? lastModified,
//     String? lastModifiedBy,
//     int? isDeleted,
//     String? deletedBy,
//     int? isSynced,
//     String? syncStatus,
//     int? syncAttempts,
//     String? lastSyncError,
//     String? bookingStatus,
//     String? paymentStatus,
//   }) {
//     return TestBooking(
//       id: id ?? original.id,
//       serverId: serverId ?? original.serverId,
//       registrationNo: registrationNo ?? original.registrationNo,
//       mrdNo: mrdNo ?? original.mrdNo,
//       date: date ?? original.date,
//       phoneNo: phoneNo ?? original.phoneNo,
//       patientName: patientName ?? original.patientName,
//       gender: gender ?? original.gender,
//       age: age ?? original.age,
//       email: email ?? original.email,
//       address: address ?? original.address,
//       doctorReferrer: doctorReferrer ?? original.doctorReferrer,
//       barcode: barcode ?? original.barcode,
//       tokenNo: tokenNo ?? original.tokenNo,
//       assignTo: assignTo ?? original.assignTo,
//       client: client ?? original.client,
//       total: total ?? original.total,
//       billDiscount: billDiscount ?? original.billDiscount,
//       totalDiscount: totalDiscount ?? original.totalDiscount,
//       gst: gst ?? original.gst,
//       totalAmount: totalAmount ?? original.totalAmount,
//       paidAmount: paidAmount ?? original.paidAmount,
//       balance: balance ?? original.balance,
//       returnAmount: returnAmount ?? original.returnAmount,
//       createdAt: createdAt ?? original.createdAt,
//       createdBy: createdBy ?? original.createdBy,
//       lastModified: lastModified ?? original.lastModified,
//       lastModifiedBy: lastModifiedBy ?? original.lastModifiedBy,
//       isDeleted: isDeleted ?? original.isDeleted,
//       deletedBy: deletedBy ?? original.deletedBy,
//       isSynced: isSynced ?? original.isSynced,
//       syncStatus: syncStatus ?? original.syncStatus,
//       syncAttempts: syncAttempts ?? original.syncAttempts,
//       lastSyncError: lastSyncError ?? original.lastSyncError,
//       bookingStatus: bookingStatus ?? original.bookingStatus,
//       paymentStatus: paymentStatus ?? original.paymentStatus,
//     );
//   }
  
//   static BookingItem copyBookingItem(BookingItem original, {
//     int? id,
//     int? serverId,
//     int? bookingId,
//     String? type,
//     String? name,
//     double? mrp,
//     double? rate,
//     int? quantity,
//     double? gstPercent,
//     double? discountPercent,
//     double? amount,
//     int? testId,
//     int? packageId,
//     String? createdAt,
//     int? isDeleted,
//     int? isSynced,
//   }) {
//     return BookingItem(
//       id: id ?? original.id,
//       serverId: serverId ?? original.serverId,
//       bookingId: bookingId ?? original.bookingId,
//       type: type ?? original.type,
//       name: name ?? original.name,
//       mrp: mrp ?? original.mrp,
//       rate: rate ?? original.rate,
//       quantity: quantity ?? original.quantity,
//       gstPercent: gstPercent ?? original.gstPercent,
//       discountPercent: discountPercent ?? original.discountPercent,
//       amount: amount ?? original.amount,
//       testId: testId ?? original.testId,
//       packageId: packageId ?? original.packageId,
//       createdAt: createdAt ?? original.createdAt,
//       isDeleted: isDeleted ?? original.isDeleted,
//       isSynced: isSynced ?? original.isSynced,
//     );
//   }
  
//   static PaymentDetail copyPaymentDetail(PaymentDetail original, {
//     int? id,
//     int? serverId,
//     int? bookingId,
//     String? paymentMode,
//     double? amount,
//     String? referenceNo,
//     String? description,
//     DateTime? paymentDate,
//     String? createdAt,
//     String? createdBy,
//     int? isDeleted,
//     int? isSynced,
//   }) {
//     return PaymentDetail(
//       id: id ?? original.id,
//       serverId: serverId ?? original.serverId,
//       bookingId: bookingId ?? original.bookingId,
//       paymentMode: paymentMode ?? original.paymentMode,
//       amount: amount ?? original.amount,
//       referenceNo: referenceNo ?? original.referenceNo,
//       description: description ?? original.description,
//       paymentDate: paymentDate ?? original.paymentDate,
//       createdAt: createdAt ?? original.createdAt,
//       createdBy: createdBy ?? original.createdBy,
//       isDeleted: isDeleted ?? original.isDeleted,
//       isSynced: isSynced ?? original.isSynced,
//     );
//   }
// }